services:
  - type: web
    name: smartstudy-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: COHERE_API_KEY
        sync: false
